InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Controllers/NewTicketController.cs
using InfoWebTicketSystem.MVC.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using InfoWebTicketSystem.MVC.ViewModels;
using System.IO;
using AutoMapper;
using InfoWebTicketSystem.BRL.Interface;

namespace InfoWebTicketSystem.MVC.Controllers
{
    public class NewTicketController : BaseController
    {

        ITicketService ticketService;
        public NewTicketController(ITicketService ticketService)
        {
            this.ticketService = ticketService;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult SelectDepartment()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SelectDepartment(SelectDepartmentViewModel modal)
        {
            if (ModelState.IsValid)
            {
                Session["SelectedDepartment"] = modal.Department;
                return RedirectToAction("CollectTicketDetail");
            }
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult CollectTicketDetail()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult CollectTicketDetail(CollectTicketDetailViewModal modal)
        {
            if (ModelState.IsValid)
            {
                if (modal.AttachedFile != null && !string.IsNullOrEmpty(modal.AttachedFile.FileName))
                {
                    modal.Attachment = ticketService.SaveUploadedFile(GetPhysicalUploadFolder(),modal.AttachedFile);
                }
                
                var ticket = Mapper.Map<CollectTicketDetailViewModal, Entities.Ticket>(modal);
               
                ticket.Department = Session["SelectedDepartment"].ToString();
                ticket.UserID = LoggedInUserAccount.ID;
                ticket.LastUpdatedUserID = LoggedInUserAccount.ID;
                ticketService.AddTicket(ticket);

                ticket = ticketService.GetTicket(ticket.ID);

                var submitConfirmationVM = Mapper.Map<Entities.Ticket, SubmitConfirmationViewModal>(ticket);
                submitConfirmationVM.Message = modal.Message;
                return View("SubmitConfirmation", submitConfirmationVM);
            }

            return View();
        }



        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Confirmation()
        {
            return View();
        }
    }
}

InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Controllers/TicketController.cs
using AutoMapper;
using InfoWebTicketSystem.BRL.Interface;
using InfoWebTicketSystem.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InfoWebTicketSystem.MVC.Controllers
{
    public class TicketController : BaseController
    {
        ITicketService ticketService;

        public TicketController(ITicketService ticketService)
        {
            this.ticketService = ticketService;
        }

        public ActionResult TicketList()
        {
            var tickLst = ticketService.GetALLTickets();
            var ttNew = new ViewModels.TicketList();
            foreach (var t in tickLst)
            {
                ttNew.Tickets.Add(Mapper.Map<Entities.Ticket, ViewModels.Ticket>(t));
            }
            return View(ttNew);
        }

        [HttpGet]
        public ActionResult ViewTicket(Guid ticketId)
        {
            var ticket = ticketService.GetTicket(ticketId);
            var vtVM = Mapper.Map<Entities.Ticket, ViewModels.ViewTicketViewModel>(ticket);
            foreach (var conv in ticket.TicketConversations)
            {

                ViewModels.TicketConversation tconv = new TicketConversation();
                tconv.Message = conv.Message;
             
                tconv.CreateDate = conv.CreateDate.Value ;
                tconv.LastUpdateDate = conv.LastUpdateDate.Value;

                if (!string.IsNullOrEmpty(conv.Attachment))
                {
                    tconv.AttachmentFileName = ticketService.GetUploadedFileName(conv.Attachment);
                    tconv.AttachmentFileRaw = "/" + GetUploadFolderName() + "/" + Path.GetFileName(conv.Attachment);
                }

                tconv.User = conv.LastUpdatedUser.UserName;
                tconv.Staff = conv.Staff ? "STAFF" : "USER";
                vtVM.Conversation.Add(tconv);

            }

           // return  View(vtVM);
            return PartialView(vtVM);
        }

        
        [HttpPost]
        public ActionResult UpdateTicket(ViewModels.ViewTicketViewModel model)
        {
            if (ModelState.IsValid)
            {
                var ticket = ticketService.GetTicket(model.ID);

               
                if (!string.IsNullOrEmpty(model.Message))
                {
                    Entities.TicketConversation conver = new Entities.TicketConversation();
                    conver.Message = model.Message;
                    conver.TicketID = ticket.ID;
                    conver.CreateDate = DateTime.Now;
                    conver.LastUpdateDate = DateTime.Now;
                    conver.ID = Guid.NewGuid();
                    conver.LastUpdatedUserID = LoggedInUserAccount.ID;
                    conver.Staff = LoggedInUserAccount.Staff;

                    if (model.AttachedFile != null && !string.IsNullOrEmpty(model.AttachedFile.FileName))
                    {
                        conver.Attachment = ticketService.SaveUploadedFile(GetPhysicalUploadFolder(), model.AttachedFile);
                    }
          
                    ticket.TicketConversations.Add(conver);
                }
                ticket.Priority = model.Priority;
                ticket.Status = model.Status;

                ticketService.UpdateTicket(ticket);
                ticket.LastUpdatedUserID = LoggedInUserAccount.ID;

                return RedirectToAction("ViewTicket", new { ticketId = ticket.ID});

            }

            return View();
        }
    }
}

InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Views/Shared/LeftPanel.cshtml
<div id="maincoreleft">
    <div id="leftloginsubscribebox">
        <div class="tabrow" id="leftloginsubscribeboxtabs">
            <a id="leftloginsubscribeboxlogintab" href="#" class="atab">
                <span class="tableftgap">
                    &nbsp;
                </span><span class="tabbulk"><span class="tabtext">Account</span></span>
            </a>
        </div>
        <div id="leftloginbox" class="switchingpanel active">
            <div class="tab-wrp">
                <div class="maitem maprofile" style="display:none" onclick="">
                    My Profile
                </div>
                <div class="maitem mapreferences" style="display:none">
                    Preferences
                </div>
                <div class="maitem machangepassword" style="display:none">
                    Change Password
                </div>
                <div class="maitem malogout" onclick="javascript:window.location.href='/Index/Logout'">
                    Logout
                </div>
            </div>
        </div>
    </div>
    <div id="leftlivechatbox">
        <!-- BEGIN FUSION TAG CODE - DO NOT EDIT! -->
        <div>
            <div id="proactivechatcontainere3rpcfy2ci">
            </div>
            <table border="0" cellspacing="2" cellpadding="2" width="100%">
                <tr>
                    <td align="center" id="swifttagcontainere3rpcfy2ci">
                        <div style="display: inline;" id="swifttagdatacontainere3rpcfy2ci">
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <!-- END FUSION TAG CODE - DO NOT EDIT! -->
    </div>
</div>

InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Views/Shared/MainLayOut.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="/Scripts/jquery-1.4.4.min.js"></script>
    @*@RenderSection("header")*@

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" />
    <title>Infoweb Services Support Desk</title>
    <meta name="KEYWORDS" content="Home" />
    <!-- <meta name="description" content="DISPLAY SOME KB STUFF OR NEWS HERE" /> -->
    <meta name="robots" content="index,follow" />
    <link rel="shortcut icon" href="/favicon.ico" />

    <link href="/StyleSheet/JuerColorPicker.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/StyleSheet/helpdesk.css" />

    <script src="/Scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
</head>
<body class="bodymain">

    <div id="main">
        <div id="topbanner">
            <!-- Custom topbanner code -->
            <table width="100%">
                <tr>
                    <td align="left">
                        <a href="index.aspx">
                            <img border="0" src="/images/InfowebServiceLogo.gif"
                                 alt="InfoWebServices Fusion Logo" id="logo" />
                        </a>
                    </td>
                    <td align="right"></td>
                </tr>
            </table>
        </div>
        <!-- Custom topbanner code end -->
        <div id="toptoolbar">
            <span id="toptoolbarrightarea">
                <select class="swiftselect" name="languageid" id="languageid" onchange="javascript: LanguageSwitch(false);">
                    <option value="1" selected=selected>English (U.S.)</option>
                    <%--
                    <option value="2">Chinese (C.N.)</option>
                    <option value="4">Türkçe</option>
                    <option value="5">??????? (Russian)</option>
                    <option value="7">Español</option>--%>
                </select>
            </span>
            <ul id="toptoolbarlinklist">
                <li>

                    @Html.ActionLink("Home", "", "Index", null,
                                               new
                                               {
                                                   style = "background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABYlBMVEUAAAAVAAAWAAAXAAAYAQEZAQEaAQEbAQE4FgE4HhREIhhGKRdHKRdVKgBhRShoSy2CXTaJYzySakKSa0OackmedkyheE4AAAAAAAAAAAAAAAAbAQEbAQFVKgAaAQEZAQEYAQEXAAAWAABVKgBVKgCnfVKedkyheE6ackmSakKSa0OJYzyCXTaAWzR0UCswAAAkBAQjBAR1VT0wAABcPigjBAQbAQEbAQEaAQEZAQEYAQEXAAAWAAAWAABAAABPPT1VQ0NZSUlmIgB5OxmQf3+RTSGSUyuVhISZVSKZVSebioqgj4+hXSykbEKllJSnYzGpmJiuajezopm0opa1cT62ckO9eUbAfErAfE3Es6rFgU7FpI3IhFHLh1TP3+/SjlvdzLvezbzf6fXi0cDl1MPo18br2snv3s3y4dDz4tH049L25dT46Nf56Nf56tv77N3869r97uD98OT+8OP+8eT/9Ol30QTQAAAAP3RSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8XHi48Pj4/QUNFRlJmaGpqbG9vcnR1eYCHip2mp6usr7O4vcLGyszsX8YvAAAA0klEQVQY0wXB206DQBQF0L33HCq32iYWLExj/CK/2pf+gi/yoImXYCRBiQVmXIsiSR48Xvtqc/mGI0nWp3arNX94XswA4NjWewReft0KR9L7mwOZRRe/hmjAqd1XfYK5+ujTJQp3flu7uSxnV18V1WT3bdoYYACtefGUH7ucTKYpIfNu9PaYeRINsAXIp8nSUiTGNxxLUGW0IlDCZ4v3a4ihsAhRiGuyE6gILYGSbPnrJTEsGlbJOResck5aB7slRbj1JxjIPDMxOWPYLLBuh0TxH4RtRL6SuvOWAAAAAElFTkSuQmCC)",
                                                   @class = "toptoolbarlink"
                                               })
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                 
                       <li class="current">
      
                                        @Html.ActionLink("View Tickets", "TicketList", "Ticket", null,
                                               new
                                               {
                                                   style = "background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABYlBMVEUAAAAVAAAWAAAXAAAYAQEZAQEaAQEbAQE4FgE4HhREIhhGKRdHKRdVKgBhRShoSy2CXTaJYzySakKSa0OackmedkyheE4AAAAAAAAAAAAAAAAbAQEbAQFVKgAaAQEZAQEYAQEXAAAWAABVKgBVKgCnfVKedkyheE6ackmSakKSa0OJYzyCXTaAWzR0UCswAAAkBAQjBAR1VT0wAABcPigjBAQbAQEbAQEaAQEZAQEYAQEXAAAWAAAWAABAAABPPT1VQ0NZSUlmIgB5OxmQf3+RTSGSUyuVhISZVSKZVSebioqgj4+hXSykbEKllJSnYzGpmJiuajezopm0opa1cT62ckO9eUbAfErAfE3Es6rFgU7FpI3IhFHLh1TP3+/SjlvdzLvezbzf6fXi0cDl1MPo18br2snv3s3y4dDz4tH049L25dT46Nf56Nf56tv77N3869r97uD98OT+8OP+8eT/9Ol30QTQAAAAP3RSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8XHi48Pj4/QUNFRlJmaGpqbG9vcnR1eYCHip2mp6usr7O4vcLGyszsX8YvAAAA0klEQVQY0wXB206DQBQF0L33HCq32iYWLExj/CK/2pf+gi/yoImXYCRBiQVmXIsiSR48Xvtqc/mGI0nWp3arNX94XswA4NjWewReft0KR9L7mwOZRRe/hmjAqd1XfYK5+ujTJQp3flu7uSxnV18V1WT3bdoYYACtefGUH7ucTKYpIfNu9PaYeRINsAXIp8nSUiTGNxxLUGW0IlDCZ4v3a4ihsAhRiGuyE6gILYGSbPnrJTEsGlbJOResck5aB7slRbj1JxjIPDMxOWPYLLBuh0TxH4RtRL6SuvOWAAAAAElFTkSuQmCC)",
                                                   @class = "toptoolbarlink"
                                               })
                    
                    </li>
                }

                <li>
                    
                    @Html.ActionLink("Submit a Ticket", "SelectDepartment", "NewTicket", null,
                                               new
                                               {
                                                   style = "background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABYlBMVEUAAAAVAAAWAAAXAAAYAQEZAQEaAQEbAQE4FgE4HhREIhhGKRdHKRdVKgBhRShoSy2CXTaJYzySakKSa0OackmedkyheE4AAAAAAAAAAAAAAAAbAQEbAQFVKgAaAQEZAQEYAQEXAAAWAABVKgBVKgCnfVKedkyheE6ackmSakKSa0OJYzyCXTaAWzR0UCswAAAkBAQjBAR1VT0wAABcPigjBAQbAQEbAQEaAQEZAQEYAQEXAAAWAAAWAABAAABPPT1VQ0NZSUlmIgB5OxmQf3+RTSGSUyuVhISZVSKZVSebioqgj4+hXSykbEKllJSnYzGpmJiuajezopm0opa1cT62ckO9eUbAfErAfE3Es6rFgU7FpI3IhFHLh1TP3+/SjlvdzLvezbzf6fXi0cDl1MPo18br2snv3s3y4dDz4tH049L25dT46Nf56Nf56tv77N3869r97uD98OT+8OP+8eT/9Ol30QTQAAAAP3RSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8XHi48Pj4/QUNFRlJmaGpqbG9vcnR1eYCHip2mp6usr7O4vcLGyszsX8YvAAAA0klEQVQY0wXB206DQBQF0L33HCq32iYWLExj/CK/2pf+gi/yoImXYCRBiQVmXIsiSR48Xvtqc/mGI0nWp3arNX94XswA4NjWewReft0KR9L7mwOZRRe/hmjAqd1XfYK5+ujTJQp3flu7uSxnV18V1WT3bdoYYACtefGUH7ucTKYpIfNu9PaYeRINsAXIp8nSUiTGNxxLUGW0IlDCZ4v3a4ihsAhRiGuyE6gILYGSbPnrJTEsGlbJOResck5aB7slRbj1JxjIPDMxOWPYLLBuh0TxH4RtRL6SuvOWAAAAAElFTkSuQmCC)",
                                                   @class = "toptoolbarlink"
                                               })
                </li>
            </ul>
        </div>
        <div id="maincore">

            @if (!User.Identity.IsAuthenticated)
            {
                @Html.Partial("_Login")
            }
            else
            {
                @Html.Partial("LeftPanel")
            }

            @RenderBody()
            <div id="bottomfooter" class="bottomfooterpadding">
            </div>
        </div>
    </div>


</body>
</html>

InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

InfowebTicketSystem_MVC4_EntityFramework/InfoWebTicketSystem.MVC/Views/Shared/_Login.cshtml
@model InfoWebTicketSystem.MVC.ViewModels.LoginViewModel

<div id="maincoreleft">
    <div id="leftloginsubscribebox">
        <div class="login-blurb">
            <div class="tabrow" id="leftloginsubscribeboxtabs">
                <a id="leftloginsubscribeboxlogintab" href="#" onclick="javascript: ActivateLoginTab();"
                   class="atab">
                    <span class="tableftgap">&nbsp;</span><span class="tabbulk">
                        <span class="tabtext">
                            Login
                            to the Helpdesk
                        </span>
                    </span>
                </a>
            </div>

            @using (Html.BeginForm("Login", "Account", FormMethod.Post, null))
            {
                @Html.AntiForgeryToken()
                <div id="leftloginbox" class="switchingpanel active">
                    <div class="lbox-wrp">
                        <input type="hidden" name="_redirectAction" value="" />
                        <div class="inputframe zebraeven">
                            <label for="email address" class="form-label">
                                Email Address
                            </label>
                            
                            @Html.TextBoxFor(model => model.UserName,
                                            new
                                               {

                                                   onfocus = "javascript: ResetLabel(this, 'Your email address', 'loginstyled')",
                                                   @Value = "maheshbailwal@gmail.com",
                                                   @class = "loginstyledlabel"
                                               })

                        </div>
                        <div class="inputframe zebraodd">
                            <label for="password" class="form-label">
                                Password
                            </label>
                            @Html.PasswordFor(model => model.Password,
                                                   new
                                                   {
                                                       @Value = "MB248001",
                                                        @class = "loginstyled"
                                                   })
                           
                        </div>
                        <div class="inputframe zebraeven">
                            <input id="leftloginboxrememberme" name="rememberme" value="1" type="checkbox"><label for="leftloginboxrememberme"><span id="leftloginboxremembermetext">Remember me</span></label>
                        </div>
                        <hr class="vdivider">
                        <div id="logintext">
                            <a href="http://www.infowebservices.in/InfowebTest/Core/ForgotPassword.aspx">
                                Lost password
                            </a>
                        </div>
                        <div id="loginsubscribebuttons">
                            <input class="rebutton" value="Login" name="Login" type="submit" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
    <script>
        function ResetLabel(obj, text, sty) {
            if ($(obj).val() == text) {
                $(obj).val("");
            }
        }

    </script>
</div>